# ----------------------------------------------------------------------
# Numenta Platform for Intelligent Computing (NuPIC)
# Copyright (C) 2013, Numenta, Inc.  Unless you have an agreement
# with Numenta, Inc., for a separate license for this software code, the
# following terms and conditions apply:
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero Public License version 3 as
# published by the Free Software Foundation.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
# See the GNU Affero Public License for more details.
#
# You should have received a copy of the GNU Affero Public License
# along with this program.  If not, see http://www.gnu.org/licenses.
#
# http://numenta.org/licenses/
# ----------------------------------------------------------------------

MODEL_PARAMS = {'aggregationInfo': {'days': 0,
                     'fields': [],
                     'hours': 0,
                     'microseconds': 0,
                     'milliseconds': 0,
                     'minutes': 0,
                     'months': 0,
                     'seconds': 0,
                     'weeks': 0,
                     'years': 0},
 'model': 'CLA',
 'modelParams': {'anomalyParams': {u'anomalyCacheRecords': None,
                                   u'autoDetectThreshold': None,
                                   u'autoDetectWaitRecords': None},
                 'clParams': {'alpha': 0.01962508905154251,
                              'clVerbosity': 0,
                              'regionName': 'CLAClassifierRegion',
                              'steps': '1'},
                 'inferenceType': 'TemporalAnomaly',
                 'sensorParams': {'encoders': {u'104': {'clipInput': True, 'fieldname': '104', 'maxval': 192,
                                                        'minval': 0, 'n': 22, 'name': '104', 'type': 'ScalarEncoder',
                                                        'w': 21},
                                               u'112': {'clipInput': True, 'fieldname': '112', 'maxval': 192,
                                                        'minval': 0, 'n': 22, 'name': '112', 'type': 'ScalarEncoder',
                                                        'w': 21},
                                               u'120': {'clipInput': True, 'fieldname': '120', 'maxval': 192,
                                                        'minval': 0, 'n': 22, 'name': '120', 'type': 'ScalarEncoder',
                                                        'w': 21},
                                               u'128': {'clipInput': True, 'fieldname': '128', 'maxval': 192,
                                                        'minval': 0, 'n': 22, 'name': '128', 'type': 'ScalarEncoder',
                                                        'w': 21},
                                               u'136': {'clipInput': True, 'fieldname': '136', 'maxval': 192,
                                                        'minval': 0, 'n': 22, 'name': '136', 'type': 'ScalarEncoder',
                                                        'w': 21},
                                               u'144': {'clipInput': True, 'fieldname': '144', 'maxval': 192,
                                                        'minval': 0, 'n': 22, 'name': '144', 'type': 'ScalarEncoder',
                                                        'w': 21},
                                               u'152': {'clipInput': True,
                                                        'fieldname': '152',
                                                        'maxval': 192,
                                                        'minval': 0,
                                                        'n': 22,
                                                        'name': '152',
                                                        'type': 'ScalarEncoder',
                                                        'w': 21},
                                               u'16': {'clipInput': True, 'fieldname': '16', 'maxval': 192, 'minval': 0,
                                                       'n': 22, 'name': '16', 'type': 'ScalarEncoder', 'w': 21},
                                               u'160': {'clipInput': True, 'fieldname': '160', 'maxval': 192,
                                                        'minval': 0, 'n': 22, 'name': '160', 'type': 'ScalarEncoder',
                                                        'w': 21},
                                               u'168': {'clipInput': True, 'fieldname': '168', 'maxval': 192,
                                                        'minval': 0, 'n': 22, 'name': '168', 'type': 'ScalarEncoder',
                                                        'w': 21},
                                               u'176': {'clipInput': True, 'fieldname': '176', 'maxval': 192,
                                                        'minval': 0, 'n': 22, 'name': '176', 'type': 'ScalarEncoder',
                                                        'w': 21},
                                               u'184': {'clipInput': True, 'fieldname': '184', 'maxval': 192,
                                                        'minval': 0, 'n': 22, 'name': '184', 'type': 'ScalarEncoder',
                                                        'w': 21},
                                               u'192': {'clipInput': True, 'fieldname': '192', 'maxval': 192,
                                                        'minval': 0, 'n': 22, 'name': '192', 'type': 'ScalarEncoder',
                                                        'w': 21},
                                               u'24': {'clipInput': True, 'fieldname': '24', 'maxval': 192, 'minval': 0,
                                                       'n': 22, 'name': '24', 'type': 'ScalarEncoder', 'w': 21},
                                               u'32': {'clipInput': True, 'fieldname': '32', 'maxval': 192, 'minval': 0,
                                                       'n': 22, 'name': '32', 'type': 'ScalarEncoder', 'w': 21},
                                               u'40': {'clipInput': True, 'fieldname': '40', 'maxval': 192, 'minval': 0,
                                                       'n': 22, 'name': '40', 'type': 'ScalarEncoder', 'w': 21},
                                               u'48': {'clipInput': True, 'fieldname': '48', 'maxval': 192, 'minval': 0,
                                                       'n': 22, 'name': '48', 'type': 'ScalarEncoder', 'w': 21},
                                               u'56': {'clipInput': True, 'fieldname': '56', 'maxval': 192, 'minval': 0,
                                                       'n': 22, 'name': '56', 'type': 'ScalarEncoder', 'w': 21},
                                               u'64': {'clipInput': True, 'fieldname': '64', 'maxval': 192, 'minval': 0,
                                                       'n': 22, 'name': '64', 'type': 'ScalarEncoder', 'w': 21},
                                               u'72': {'clipInput': True, 'fieldname': '72', 'maxval': 192, 'minval': 0,
                                                       'n': 22, 'name': '72', 'type': 'ScalarEncoder', 'w': 21},
                                               u'8': {'clipInput': True, 'fieldname': '8', 'maxval': 192, 'minval': 0,
                                                      'n': 22, 'name': '8', 'type': 'ScalarEncoder', 'w': 21},
                                               u'80': {'clipInput': True, 'fieldname': '80', 'maxval': 192, 'minval': 0,
                                                       'n': 22, 'name': '80', 'type': 'ScalarEncoder', 'w': 21},
                                               u'88': {'clipInput': True, 'fieldname': '88', 'maxval': 192, 'minval': 0,
                                                       'n': 22, 'name': '88', 'type': 'ScalarEncoder', 'w': 21},
                                               u'96': {'clipInput': True, 'fieldname': '96', 'maxval': 192, 'minval': 0,
                                                       'n': 22, 'name': '96', 'type': 'ScalarEncoder', 'w': 21},
                                               u'timestamp_dayOfWeek': None,
                                               u'timestamp_timeOfDay': None,
                                               u'timestamp_weekend': {'fieldname': 'timestamp',
                                                                      'name': 'timestamp',
                                                                      'type': 'DateEncoder',
                                                                      'weekend': (21, 1)}},
                                  'sensorAutoReset': None,
                                  'verbosity': 0},
                 'spEnable': True,
                 'spParams': {'columnCount': 2048,
                              'globalInhibition': 1,
                              'inputWidth': 0,
                              'maxBoost': 1.0,
                              'numActiveColumnsPerInhArea': 40,
                              'potentialPct': 0.8,
                              'seed': 1956,
                              'spVerbosity': 0,
                              'spatialImp': 'cpp',
                              'synPermActiveInc': 0.0015,
                              'synPermConnected': 0.1,
                              'synPermInactiveDec': 0.0005},
                 'tpEnable': True,
                 'tpParams': {'activationThreshold': 13,
                              'cellsPerColumn': 32,
                              'columnCount': 2048,
                              'globalDecay': 0.0,
                              'initialPerm': 0.21,
                              'inputWidth': 2048,
                              'maxAge': 0,
                              'maxSegmentsPerCell': 128,
                              'maxSynapsesPerSegment': 32,
                              'minThreshold': 10,
                              'newSynapseCount': 20,
                              'outputType': 'normal',
                              'pamLength': 3,
                              'permanenceDec': 0.1,
                              'permanenceInc': 0.1,
                              'seed': 1960,
                              'temporalImp': 'cpp',
                              'verbosity': 0},
                 'trainSPNetOnlyIfRequested': False},
 'predictAheadTime': None,
 'version': 1}
